package dns

import (
	"net/netip"
	"path/filepath"
	"strings"
	"testing"
)

func testBackend(t *testing.T) Backend {
	t.Helper()
	return NewBackend(RootedPaths(t.TempDir())).WithSource("/etc/open-linux-router/olr.json")
}

func renderOne(t *testing.T, b Backend, c Config, path string) string {
	t.Helper()
	out, err := b.Render(c, testLinks())
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	f, ok := out.Get(path)
	if !ok {
		t.Fatalf("nothing rendered at %s; got %v", path, out.Paths())
	}
	return string(f.Data)
}

// renderDirectives is the rendered file reduced to what the daemon actually
// reads — comments and blank lines gone.
//
// Assertions about behaviour belong against this rather than against the raw
// file. Roughly half of what we render is prose explaining the directive below
// it, so a test looking for "forward-zone" or "reject" in the raw bytes matches
// the sentence saying why we do not use one.
func renderDirectives(t *testing.T, b Backend, c Config, path string) string {
	t.Helper()
	return string(b.Canonical([]byte(renderOne(t, b, c, path))))
}

// Drift detection compares rendered bytes against what is on disk, so a
// renderer that is not a pure function of its inputs would make every box look
// permanently drifted.
func TestRenderIsDeterministic(t *testing.T) {
	b := testBackend(t)
	cfg := validConfig()
	cfg.Policies = []Policy{
		{Name: "kids", Clients: []netip.Prefix{netip.MustParsePrefix("192.168.1.50/32")},
			Block: []string{"b.example", "a.example"}},
		{Name: "default", Block: []string{"ads.example"}},
	}
	cfg.Hijack = Hijack{Enabled: true, Interfaces: []string{"lan0"}, BlockDoT: true}

	first, err := b.Render(cfg, testLinks())
	if err != nil {
		t.Fatal(err)
	}
	second, err := b.Render(cfg, testLinks())
	if err != nil {
		t.Fatal(err)
	}

	if len(first.Files) != len(second.Files) {
		t.Fatalf("file count differs: %d vs %d", len(first.Files), len(second.Files))
	}
	for i := range first.Files {
		if first.Files[i].Path != second.Files[i].Path {
			t.Errorf("file %d: path %s vs %s", i, first.Files[i].Path, second.Files[i].Path)
		}
		if string(first.Files[i].Data) != string(second.Files[i].Data) {
			t.Errorf("%s rendered differently on a second call", first.Files[i].Path)
		}
	}
}

// Every generated file carries an ownership header naming the file that
// produced it (design.md §7). JSON has no comments, so relay.json and the
// policy files are the documented exception.
func TestRenderedFilesCarryAnOwnershipHeader(t *testing.T) {
	b := testBackend(t)
	cfg := validConfig()
	cfg.Hijack = Hijack{Enabled: true, Interfaces: []string{"lan0"}}

	out, err := b.Render(cfg, testLinks())
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range out.Files {
		if strings.HasSuffix(f.Path, ".json") {
			continue
		}
		body := string(f.Data)
		if !strings.Contains(body, "Generated by open-linux-router") {
			t.Errorf("%s has no ownership header", f.Path)
		}
		if !strings.Contains(body, "/etc/open-linux-router/olr.json") {
			t.Errorf("%s does not name the file that produced it", f.Path)
		}
	}
}

func TestRenderUnbound(t *testing.T) {
	b := testBackend(t)
	conf := renderDirectives(t, b, validConfig(), b.Paths.UnboundConf)

	// unbound must be unreachable from the network by construction, not by
	// firewall rule: the relay owns :53 and this sits behind it on loopback.
	for _, want := range []string{
		"interface: 127.0.0.1@5353",
		"access-control: 0.0.0.0/0 refuse",
		"access-control: 127.0.0.0/8 allow",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("unbound.conf is missing %q:\n%s", want, conf)
		}
	}
	if strings.Contains(conf, "interface: 0.0.0.0") {
		t.Error("unbound was told to listen on the wildcard")
	}
}

// The one range deliberately absent from the rebinding list.
//
// olr does not route by domain name and so has no use for a fake IP of its own
// (docs/gateway.md §4). This guards somebody else's setup: an operator running
// mihomo in fake-IP mode with `upstream` pointed at its resolver would have
// every answer stripped, with the cause a line in a rendered config they have
// no reason to suspect.
func TestRenderDoesNotStripTheBenchmarkingRange(t *testing.T) {
	b := testBackend(t)
	conf := renderDirectives(t, b, validConfig(), b.Paths.UnboundConf)

	if !strings.Contains(conf, "private-address: 192.168.0.0/16") {
		t.Error("rebinding protection is not configured at all")
	}
	if strings.Contains(conf, "198.18.") {
		t.Error("198.18.0.0/15 is in the rebinding list; that silently breaks a fake-IP proxy behind us")
	}
}

func TestRenderForwarding(t *testing.T) {
	b := testBackend(t)

	t.Run("recursing renders no forward zone", func(t *testing.T) {
		conf := renderDirectives(t, b, validConfig(), b.Paths.UnboundConf)
		if strings.Contains(conf, "forward-zone") {
			t.Errorf("a forward-zone was rendered in recursing mode:\n%s", conf)
		}
	})

	t.Run("plaintext", func(t *testing.T) {
		cfg := validConfig()
		cfg.Upstream = Upstream{Mode: ModeForward, Servers: []netip.AddrPort{
			netip.AddrPortFrom(netip.MustParseAddr("1.1.1.1"), 0),
		}}
		conf := renderDirectives(t, b, cfg, b.Paths.UnboundConf)
		if !strings.Contains(conf, "forward-addr: 1.1.1.1@53") {
			t.Errorf("a portless forwarder did not default to 53:\n%s", conf)
		}
	})

	t.Run("DoT defaults to 853 and pins the name", func(t *testing.T) {
		// The difference between "1.1.1.1 with tls on" working and silently
		// trying DoT against plaintext 53.
		cfg := validConfig()
		cfg.Upstream = Upstream{
			Mode:    ModeForward,
			Servers: []netip.AddrPort{netip.AddrPortFrom(netip.MustParseAddr("1.1.1.1"), 0)},
			TLS:     true,
			TLSName: "cloudflare-dns.com",
		}
		conf := renderDirectives(t, b, cfg, b.Paths.UnboundConf)
		if !strings.Contains(conf, "forward-tls-upstream: yes") {
			t.Error("TLS was not enabled on the forward zone")
		}
		if !strings.Contains(conf, "forward-addr: 1.1.1.1@853#cloudflare-dns.com") {
			t.Errorf("the forwarder was not rendered with the DoT port and name:\n%s", conf)
		}
	})
}

func TestRenderRelayDerivesAllowFromTheListenNetworks(t *testing.T) {
	b := testBackend(t)
	cfg := validConfig()
	cfg.AllowFrom = nil

	relay := renderOne(t, b, cfg, b.Paths.RelayConf)
	if !strings.Contains(relay, "192.168.1.0/24") {
		t.Errorf("an empty allow_from did not derive the listen network:\n%s", relay)
	}
	// Never open. An empty list denies everybody in the relay, and deriving is
	// the only reading that cannot accidentally ship an amplifier.
	if strings.Contains(relay, "0.0.0.0/0") {
		t.Error("the derived access list is open")
	}
}

func TestRenderRelayPointsAtUnbound(t *testing.T) {
	b := testBackend(t)
	relay := renderOne(t, b, validConfig(), b.Paths.RelayConf)
	if !strings.Contains(relay, "127.0.0.1:5353") {
		t.Errorf("the relay was not pointed at unbound:\n%s", relay)
	}
}

// The query log is off unless asked for, and the relay reads that as "keep
// nothing" rather than as a default size.
func TestRenderRelayQueryLog(t *testing.T) {
	b := testBackend(t)

	off := renderOne(t, b, validConfig(), b.Paths.RelayConf)
	if strings.Contains(off, "query_log_entries") {
		t.Errorf("a disabled query log still rendered a capacity:\n%s", off)
	}

	cfg := validConfig()
	cfg.QueryLog = QueryLog{Enabled: true}
	on := renderOne(t, b, cfg, b.Paths.RelayConf)
	if !strings.Contains(on, "query_log_entries") {
		t.Errorf("an enabled query log rendered no capacity:\n%s", on)
	}
}

// Policies live in a directory because the relay re-reads it on SIGHUP. That is
// what makes editing a blocklist — much the most common change — free.
func TestRenderPoliciesAreReloadable(t *testing.T) {
	b := testBackend(t)
	cfg := validConfig()
	cfg.Policies = []Policy{{Name: "kids", Block: []string{"example.com"}}}

	out, err := b.Render(cfg, testLinks())
	if err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(b.Paths.PolicyDir, "kids.json")
	f, ok := out.Get(path)
	if !ok {
		t.Fatalf("no policy file at %s; got %v", path, out.Paths())
	}
	if !f.Reloadable {
		t.Error("a policy file is not marked reloadable, so editing a blocklist would restart DNS")
	}
	if f.Unit != b.RelayUnit() {
		t.Errorf("policy file belongs to %q, want %q", f.Unit, b.RelayUnit())
	}
	if !strings.Contains(string(f.Data), "example.com") {
		t.Errorf("the blocked name is not in the rendered policy:\n%s", f.Data)
	}
	// The default response has to be explicit in the file: the relay must not
	// have to know what an empty string means here.
	if !strings.Contains(string(f.Data), string(RespondNXDOMAIN)) {
		t.Errorf("the policy did not render a response:\n%s", f.Data)
	}
}

// Nothing about the resolver's own configuration changes when a blocklist does,
// so a policy edit must not touch unbound's file at all.
func TestRenderSeparatesTheTwoBackends(t *testing.T) {
	b := testBackend(t)

	before := renderOne(t, b, validConfig(), b.Paths.UnboundConf)

	cfg := validConfig()
	cfg.Policies = []Policy{{Name: "kids", Block: []string{"example.com"}}}
	after := renderOne(t, b, cfg, b.Paths.UnboundConf)

	if before != after {
		t.Error("adding a blocklist changed unbound's configuration, which would restart the resolver")
	}
}

func TestRenderHijack(t *testing.T) {
	b := testBackend(t)
	cfg := validConfig()
	cfg.Listen = append(cfg.Listen, netip.MustParseAddrPort("[fd00::1]:53"))
	cfg.AllowFrom = append(cfg.AllowFrom, netip.MustParsePrefix("fd00::/64"))
	cfg.Hijack = Hijack{Enabled: true, Interfaces: []string{"lan0"}, BlockDoT: true}
	cfg.Normalize()

	nft := renderDirectives(t, b, cfg, b.Paths.HijackNFT)

	// The idempotent flush-and-recreate form: nft refuses to delete a table
	// that is not there, and this file has to survive being loaded twice.
	if !strings.Contains(nft, "table inet olr-dns\ndelete table inet olr-dns") {
		t.Errorf("the ruleset is not idempotent:\n%s", nft)
	}
	for _, want := range []string{
		`iifname { "lan0" } ip daddr != 192.168.1.1 udp dport 53 dnat ip to 192.168.1.1:53`,
		`iifname { "lan0" } ip daddr != 192.168.1.1 tcp dport 53 dnat ip to 192.168.1.1:53`,
		`dnat ip6 to [fd00::1]:53`,
		"tcp dport 853 drop",
		"udp dport 853 drop",
	} {
		if !strings.Contains(nft, want) {
			t.Errorf("the ruleset is missing %q:\n%s", want, nft)
		}
	}
	// A reject tells the client to fall back immediately; the whole point is
	// that it does not.
	if strings.Contains(nft, "reject") {
		t.Error("DoT is rejected rather than dropped, which makes falling back instant")
	}
}

func TestRenderHijackIsAbsentWhenOff(t *testing.T) {
	b := testBackend(t)
	out, err := b.Render(validConfig(), testLinks())
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := out.Get(b.Paths.HijackNFT); ok {
		t.Error("a ruleset was rendered with the redirect off")
	}
}

func TestRenderHijackWithoutDoTBlockingOmitsTheChain(t *testing.T) {
	b := testBackend(t)
	cfg := validConfig()
	cfg.Hijack = Hijack{Enabled: true, Interfaces: []string{"lan0"}}
	nft := renderDirectives(t, b, cfg, b.Paths.HijackNFT)
	if strings.Contains(nft, "853") {
		t.Errorf("a forward chain was rendered with DoT blocking off:\n%s", nft)
	}
}

// Roughly half of what we render is explanation. Without normalisation,
// rewording a comment in a new olr release would mark every deployed box as
// drifted and restart its resolver.
func TestCanonicalIgnoresComments(t *testing.T) {
	b := testBackend(t)
	withComments := []byte("# one explanation\nserver:\n\n  # another\n  verbosity: 0\n")
	reworded := []byte("# a better explanation\nserver:\n  verbosity: 0\n")

	if string(b.Canonical(withComments)) != string(b.Canonical(reworded)) {
		t.Errorf("rewording a comment changed the canonical form:\n%q\n%q",
			b.Canonical(withComments), b.Canonical(reworded))
	}
	if string(b.Canonical(withComments)) == string(b.Canonical([]byte("server:\n  verbosity: 1\n"))) {
		t.Error("a real change was normalised away")
	}
}

func TestUnitForClassifiesStrayFiles(t *testing.T) {
	b := testBackend(t)
	tests := map[string]string{
		b.Paths.UnboundConf: b.ResolverUnit(),
		b.Paths.RelayConf:   b.RelayUnit(),
		b.Paths.HijackNFT:   b.RelayUnit(),
		filepath.Join(b.Paths.PolicyDir, "stale.json"): b.RelayUnit(),
		"/etc/somewhere/else":                          "",
	}
	for path, want := range tests {
		if got := b.unitFor(path); got != want {
			t.Errorf("unitFor(%s) = %q, want %q", path, got, want)
		}
	}
}
