// Package iptv controls routed IPv4 IPTV multicast, not an L2 IPTV bridge.
package iptv

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/netip"
	"slices"
	"strings"
	"unicode"

	"github.com/open-linux-router/open-linux-router/internal/core"
)

const ModuleName = "iptv"
const UnitName = "olr-iptv.service"

// Config names one multicast upstream and the LANs allowed to subscribe.
type Config struct {
	Enabled  bool           `json:"enabled"`
	Upstream string         `json:"upstream,omitempty"`
	Networks []string       `json:"networks,omitempty"`
	Sources  []netip.Prefix `json:"sources,omitempty"`
}

func UnmarshalConfig(data []byte) (Config, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var c Config
	if err := dec.Decode(&c); err != nil {
		return c, fmt.Errorf("iptv configuration: %w", err)
	}
	if err := dec.Decode(new(any)); err != io.EOF {
		return Config{}, fmt.Errorf("iptv configuration: trailing JSON: %v", err)
	}
	return c, nil
}
func MarshalConfig(c Config) ([]byte, error) { return json.Marshal(c) }
func FromDocument(d core.Document) (Config, error) {
	raw, ok := d.Raw(ModuleName)
	if !ok {
		return Config{}, nil
	}
	return UnmarshalConfig(raw)
}

// Network is the link module's current view; IPTV does not own LAN interfaces.
type Network struct {
	Name    string
	Members []string
	IPv4    bool
}
type Links interface {
	Interface(name string) (adopted, present, ipv4 bool, err error)
	Networks() ([]Network, error)
	Interfaces() ([]string, error)
}

type Resolved struct {
	Upstream   string
	Downstream []string
	Sources    []netip.Prefix
	Disabled   []string
}

func Resolve(c Config, links Links) (Resolved, error) {
	if !c.Enabled {
		return Resolved{}, nil
	}
	if c.Upstream == "" {
		return Resolved{}, fmt.Errorf("upstream: select an adopted IPTV interface")
	}
	adopted, present, ipv4, err := links.Interface(c.Upstream)
	if err != nil {
		return Resolved{}, err
	}
	if !adopted || !present || !ipv4 || unsafeInterface(c.Upstream) {
		return Resolved{}, fmt.Errorf("upstream: %q must be adopted, present, and have an IPv4 address", c.Upstream)
	}
	if len(c.Networks) == 0 {
		return Resolved{}, fmt.Errorf("networks: select at least one downstream network")
	}
	all, err := links.Networks()
	if err != nil {
		return Resolved{}, err
	}
	out := Resolved{Upstream: c.Upstream, Sources: c.Sources}
	for _, prefix := range c.Sources {
		if !prefix.IsValid() || !prefix.Addr().Is4() || prefix.Addr().IsMulticast() || prefix.Addr().IsUnspecified() || prefix.Addr().IsLoopback() || prefix.Bits() == 0 {
			return Resolved{}, fmt.Errorf("sources: %s must be a unicast IPv4 prefix", prefix)
		}
	}
	seen := map[string]bool{}
	for _, name := range c.Networks {
		if seen[name] {
			return Resolved{}, fmt.Errorf("networks: duplicate %q", name)
		}
		seen[name] = true
		idx := slices.IndexFunc(all, func(n Network) bool { return n.Name == name })
		if idx < 0 {
			return Resolved{}, fmt.Errorf("networks: unknown network %q", name)
		}
		n := all[idx]
		if !n.IPv4 || len(n.Members) != 1 || n.Members[0] == c.Upstream || unsafeInterface(n.Members[0]) {
			return Resolved{}, fmt.Errorf("networks: %q must have one IPv4 member distinct from the upstream", name)
		}
		if slices.Contains(out.Downstream, n.Members[0]) {
			return Resolved{}, fmt.Errorf("networks: member %q selected twice", n.Members[0])
		}
		out.Downstream = append(out.Downstream, n.Members[0])
	}
	for _, n := range all {
		if slices.Contains(n.Members, c.Upstream) {
			return Resolved{}, fmt.Errorf("upstream: %q is a LAN member; choose a separate IPTV interface", c.Upstream)
		}
	}
	interfaces, err := links.Interfaces()
	if err != nil {
		return Resolved{}, err
	}
	for _, down := range out.Downstream {
		if !slices.Contains(interfaces, down) {
			return Resolved{}, fmt.Errorf("networks: member %q is not present", down)
		}
	}
	for _, iface := range interfaces {
		if unsafeInterface(iface) {
			return Resolved{}, fmt.Errorf("interface %q contains whitespace or a control character", iface)
		}
		if iface != out.Upstream && !slices.Contains(out.Downstream, iface) {
			out.Disabled = append(out.Disabled, iface)
		}
	}
	slices.Sort(out.Downstream)
	slices.Sort(out.Disabled)
	return out, nil
}

func unsafeInterface(name string) bool {
	if name == "" {
		return true
	}
	return strings.IndexFunc(name, func(r rune) bool { return unicode.IsSpace(r) || unicode.IsControl(r) }) >= 0
}

// Render never includes unspecified interfaces: igmpproxy otherwise enables them.
func Render(r Resolved) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Generated by olr; do not edit.\nphyint %s upstream\n", r.Upstream)
	for _, source := range r.Sources {
		fmt.Fprintf(&b, "altnet %s\n", source)
	}
	for _, iface := range r.Downstream {
		fmt.Fprintf(&b, "phyint %s downstream\n", iface)
	}
	for _, iface := range r.Disabled {
		fmt.Fprintf(&b, "phyint %s disabled\n", iface)
	}
	return b.Bytes()
}
