package main

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"unicode"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// The rules in docs/cli.md, as assertions.
//
// These live here rather than in internal/cli because this is the only package
// that can see the whole tree: modules are mounted by newRoot, and the tests
// that used to walk cli.NewRoot() were walking a tree with no modules in it.
// Every rule below describes drift those tests could not see.

var update = flag.Bool("update", false, "rewrite the --help golden files")

// ---------------------------------------------------------------- walking

// walk visits every command an operator can reach, skipping cobra's built-ins.
//
// `help` and `completion` are generated by cobra, so their text and argument
// shapes are not ours to hold to these rules — and asserting on them would turn
// a cobra upgrade into a conformance failure.
func walk(t *testing.T, fn func(*testing.T, *cobra.Command)) {
	t.Helper()
	root := newRoot()
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()

	var visit func(*cobra.Command)
	visit = func(c *cobra.Command) {
		if builtin(c) {
			return
		}
		if c.HasParent() {
			t.Run(strings.ReplaceAll(c.CommandPath(), " ", "_"), func(t *testing.T) {
				fn(t, c)
			})
		}
		for _, sub := range c.Commands() {
			visit(sub)
		}
	}
	visit(root)
}

func builtin(c *cobra.Command) bool {
	for cur := c; cur != nil; cur = cur.Parent() {
		switch cur.Name() {
		case "help", "completion":
			return true
		}
	}
	return false
}

func leaf(c *cobra.Command) bool { return !c.HasSubCommands() }

// ---------------------------------------------------------------- R1

// placeholderPattern is docs/cli.md R1: a lower-case command name, then
// placeholders that are lower-case in angle brackets, optional ones in square
// brackets outside those, a closed literal choice like `on|off`, and at most a
// trailing ellipsis.
var placeholderPattern = regexp.MustCompile(
	`^[a-z][a-z0-9-]*(\s+(<[a-z][a-z-]*>|\[<[a-z][a-z-]*>\]|[a-z]+(\|[a-z]+)+)(\.\.\.)?)*$`)

func TestPlaceholderStyle(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		if !placeholderPattern.MatchString(c.Use) {
			t.Errorf("Use = %q\nwant lower-case <angle-bracket> placeholders — see docs/cli.md R1", c.Use)
		}
	})
}

// token describes one placeholder in a Use string.
type token struct {
	optional bool
	variadic bool
}

func placeholders(use string) []token {
	fields := strings.Fields(use)
	if len(fields) < 2 {
		return nil
	}
	out := make([]token, 0, len(fields)-1)
	for _, f := range fields[1:] {
		tk := token{variadic: strings.HasSuffix(f, "...")}
		f = strings.TrimSuffix(f, "...")
		tk.optional = strings.HasPrefix(f, "[")
		out = append(out, tk)
	}
	return out
}

func arity(tokens []token) (req, opt int, variadic bool) {
	for _, tk := range tokens {
		switch {
		case tk.optional:
			opt++
		default:
			req++
		}
		if tk.variadic {
			variadic = true
		}
	}
	return req, opt, variadic
}

// TestOptionalPlaceholdersComeLast keeps the Use string readable as a grammar:
// `via <network> [<exit>]` is meaningful, `via [<network>] <exit>` is not
// something a positional parser could honour anyway.
func TestOptionalPlaceholdersComeLast(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		seenOptional := false
		for _, tk := range placeholders(c.Use) {
			if tk.optional {
				seenOptional = true
				continue
			}
			if seenOptional {
				t.Errorf("Use = %q has a required placeholder after an optional one", c.Use)
				return
			}
		}
	})
}

// ---------------------------------------------------------------- R1 × Args

// TestArgsMatchPlaceholders is the rule that earns its place beyond style: it
// catches a command that advertises `<network> <exit>` and validates
// ExactArgs(1), which is a real defect wearing a formatting defect's clothes.
//
// cobra's Args is a function rather than data, so this exercises it instead of
// inspecting it — the check is what the command would actually accept.
func TestArgsMatchPlaceholders(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		if c.RunE == nil && c.Run == nil {
			return // a pure group; cobra reports unknown subcommands itself
		}
		if c.Args == nil {
			t.Fatalf("has no Args validator; every runnable command must declare one")
		}

		req, opt, variadic := arity(placeholders(c.Use))

		accepts := func(n int) bool { return c.Args(c, sampleArgs(c, n)) == nil }

		if !accepts(req) {
			t.Errorf("Use = %q promises %d required argument(s), but Args rejects %d", c.Use, req, req)
		}
		if req > 0 && accepts(req-1) {
			t.Errorf("Use = %q promises %d required argument(s), but Args accepts %d", c.Use, req, req-1)
		}
		if opt > 0 && !accepts(req+opt) {
			t.Errorf("Use = %q allows %d optional argument(s), but Args rejects %d", c.Use, opt, req+opt)
		}
		if !variadic && accepts(req+opt+1) {
			t.Errorf("Use = %q takes at most %d argument(s), but Args accepts %d", c.Use, req+opt, req+opt+1)
		}
		if variadic && !accepts(req+opt+2) {
			t.Errorf("Use = %q is variadic, but Args rejects %d arguments", c.Use, req+opt+2)
		}
	})
}

// sampleArgs draws from ValidArgs where the command declares them, so a
// value-checking validator is exercised with values it should accept.
func sampleArgs(c *cobra.Command, n int) []string {
	out := make([]string, n)
	for i := range out {
		if len(c.ValidArgs) > 0 {
			out[i] = c.ValidArgs[i%len(c.ValidArgs)]
			continue
		}
		out[i] = "sample"
	}
	return out
}

// ---------------------------------------------------------------- R3, R5

// TestBoolFlagsDefaultFalse is docs/cli.md R3. pflag takes no space-separated
// value for a boolean, so a flag defaulting true can only be turned off as
// `--flag=false`; written the natural way it silently becomes the flag plus a
// stray positional, and the error names the argument count rather than the
// mistake.
func TestBoolFlagsDefaultFalse(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		eachFlag(c, func(f *pflag.Flag) {
			if f.Value.Type() == "bool" && f.DefValue == "true" {
				t.Errorf("--%s is a boolean defaulting true; give it a --no-%s partner and default both false",
					f.Name, f.Name)
			}
		})
	})
}

// TestNegativeFlagsArePaired is R3 and R4's other half: a --no-x that has no
// --x leaves the operator no way back, and a --x with no --no-x leaves no way
// to clear it except the empty string R4 exists to abolish.
func TestNegativeFlagsArePaired(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		names := map[string]bool{}
		eachFlag(c, func(f *pflag.Flag) { names[f.Name] = true })
		for name := range names {
			positive, ok := strings.CutPrefix(name, "no-")
			if !ok {
				continue
			}
			// The positive form may be a positional rather than a flag: R2 puts
			// identity in the argument, so `set default [<exit>]` says the
			// affirmative and `--no-exit` says the negative, and that pair is
			// complete without a --exit nobody would ever type.
			if names[positive] || strings.Contains(c.Use, "<"+positive+">") {
				continue
			}
			t.Errorf("--%s has no --%s and no <%s> argument to undo", name, positive, positive)
		}
	})
}

// TestMultiValueFlagsAreArrays is R5. StringSlice splits on commas and
// StringArray does not, and the surface shipped both with nothing in --help to
// tell them apart — so a value containing a comma was silently cut in half in
// some flags and not others.
func TestMultiValueFlagsAreArrays(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		eachFlag(c, func(f *pflag.Flag) {
			if strings.HasSuffix(f.Value.Type(), "Slice") {
				t.Errorf("--%s is a %s; multi-value flags are repeatable arrays, not comma-split slices",
					f.Name, f.Value.Type())
			}
		})
	})
}

// TestRepeatableFlagsSaySo keeps the help text honest about R5: a flag the
// operator must repeat should say it, since nothing else on screen does.
func TestRepeatableFlagsSaySo(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		eachFlag(c, func(f *pflag.Flag) {
			if !strings.HasSuffix(f.Value.Type(), "Array") {
				return
			}
			if !strings.Contains(f.Usage, "repeatable") {
				t.Errorf("--%s takes repeated values but its help does not say \"repeatable\": %q",
					f.Name, f.Usage)
			}
		})
	})
}

func eachFlag(c *cobra.Command, fn func(*pflag.Flag)) {
	c.LocalFlags().VisitAll(fn)
}

// ---------------------------------------------------------------- R6

// TestShowCommandsAreListOrDetail is R6. The banned shape is one command doing
// both jobs — `policies [name]` — which cannot describe itself in one line and
// cannot complete its argument, since whether a name is wanted depends on an
// intent the completer has no way to read.
func TestShowCommandsAreListOrDetail(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		if c.Parent() == nil || c.Parent().Name() != "show" {
			return
		}
		req, opt, _ := arity(placeholders(c.Use))
		if opt > 0 {
			t.Errorf("Use = %q takes an optional argument; split it into a list command and a detail command", c.Use)
		}
		if req > 1 {
			t.Errorf("Use = %q takes %d arguments; a detail command names one object", c.Use, req)
		}
	})
}

// ---------------------------------------------------------------- R7

// TestObjectPlaceholdersHaveCompletion is R7, scoped to the verbs that always
// address something that already exists. `add` is exempt: it is naming a new
// object, and completing it from what exists would suggest precisely the names
// that are about to be rejected as duplicates.
func TestObjectPlaceholdersHaveCompletion(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		if !leaf(c) || !underVerb(c, "rm", "set") {
			return
		}
		if req, opt, _ := arity(placeholders(c.Use)); req+opt == 0 {
			return
		}
		if onlyPlaceholderIs(c.Use, "<file>") {
			return // a path; the shell's own file completion is the right answer
		}
		if c.ValidArgsFunction == nil && len(c.ValidArgs) == 0 {
			t.Errorf("Use = %q names an existing object but completes nothing", c.Use)
		}
	})
}

func underVerb(c *cobra.Command, verbs ...string) bool {
	for cur := c; cur != nil; cur = cur.Parent() {
		for _, v := range verbs {
			if cur.Name() == v {
				return true
			}
		}
	}
	return false
}

func onlyPlaceholderIs(use, want string) bool {
	fields := strings.Fields(use)
	return len(fields) == 2 && fields[1] == want
}

// ---------------------------------------------------------------- help text

func TestEveryCommandHasShortHelp(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		switch {
		case c.Short == "":
			t.Error("has no Short description")
		case strings.HasSuffix(c.Short, "."):
			t.Errorf("Short = %q ends with a period; the others do not", c.Short)
		case !unicode.IsUpper([]rune(c.Short)[0]):
			t.Errorf("Short = %q does not start with a capital", c.Short)
		case len(c.Short) > 78:
			t.Errorf("Short is %d characters; keep it under 78 so --help does not wrap", len(c.Short))
		}
	})
}

func TestEveryLeafCommandRuns(t *testing.T) {
	walk(t, func(t *testing.T, c *cobra.Command) {
		if leaf(c) && c.RunE == nil && c.Run == nil {
			t.Error("is a leaf command with nothing to run")
		}
	})
}

func TestTopLevelCommandsAreGrouped(t *testing.T) {
	root := newRoot()
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	for _, c := range root.Commands() {
		if c.GroupID == "" {
			t.Errorf("command %q has no GroupID; cobra would file it under an untitled heading", c.Name())
		}
	}
}

// ---------------------------------------------------------------- goldens

// TestHelpIsUnchanged snapshots the text that *is* the contract this whole
// document is about. A reworded Short or a renamed flag should arrive as a diff
// somebody reads, not as a surprise for whoever hits it next.
//
// Regenerate with `go test ./cmd/olr -run TestHelpIsUnchanged -update`.
func TestHelpIsUnchanged(t *testing.T) {
	for _, path := range [][]string{
		{},
		{"link"}, {"link", "show"}, {"adopt"}, {"release"},
		{"dhcp"}, {"dhcp", "show"}, {"dhcp", "add"}, {"dhcp", "set"}, {"dhcp", "rm"},
		{"dns"}, {"dns", "show"}, {"dns", "add"}, {"dns", "set"}, {"dns", "rm"},
		{"gateway"}, {"gateway", "show"}, {"gateway", "add"}, {"gateway", "set"}, {"gateway", "rm"},
		{"firewall"}, {"firewall", "show"}, {"firewall", "add"}, {"firewall", "set"}, {"firewall", "rm"},
		{"ingress"}, {"ingress", "show"}, {"ingress", "add"}, {"ingress", "set"}, {"ingress", "rm"},
		{"listen"}, {"status"}, {"enable"}, {"disable"},
	} {
		name := "olr"
		if len(path) > 0 {
			name = strings.Join(path, "_")
		}
		t.Run(name, func(t *testing.T) {
			var out bytes.Buffer
			root := newRoot()
			root.SetOut(&out)
			root.SetErr(&out)
			root.SetArgs(append(append([]string{}, path...), "--help"))
			if err := root.Execute(); err != nil {
				t.Fatalf("--help returned %v", err)
			}

			golden := filepath.Join("testdata", name+".help")
			if *update {
				if err := os.MkdirAll("testdata", 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(golden, out.Bytes(), 0o644); err != nil {
					t.Fatal(err)
				}
				return
			}
			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("%v\nrun `go test ./cmd/olr -run TestHelpIsUnchanged -update` to create it", err)
			}
			if got := out.String(); got != string(want) {
				t.Errorf("--help changed.\n--- want ---\n%s\n--- got ---\n%s", want, got)
			}
		})
	}
}
