// Package ouidb answers "who made this hardware address" from the IEEE
// registry.
//
// It is the database internal/devices/detect.go spent its first release
// deferring: a hand-seeded list of forty prefixes named a vendor for the
// handful of devices someone had thought to add, and said nothing about every
// other device on the network. Saying nothing is the honest failure, but on a
// network where DHCP is off and therefore no client has announced a hostname,
// it is also every row — a list of six identical hex strings, which is not an
// inventory.
//
// # What it is not
//
// A vendor is not an identity and not a category. It answers who built the
// hardware, which for Apple or Samsung narrows a device to "one of about
// forty products". Detect keeps the two apart for that reason, and the
// hand-seeded table there still outranks this one: see ouiTable.
//
// # Shape
//
// One table, three block sizes, longest match wins. The data is generated by
// gen.go and committed, so a build needs no network and two builds of one
// commit embed the same bytes. See oui.gz's header line for which day's
// registry that is.
package ouidb

import (
	"bytes"
	"compress/gzip"
	"io"
	"strings"
	"sync"

	_ "embed"

	"github.com/open-linux-router/open-linux-router/internal/core"
)

// packed is the generated table: gzipped, because 1.3 MB of mostly-ASCII
// compresses to under 500 kB and this file is linked into olr, where an
// icon's size is already treated as the binary's size.
//
//go:embed oui.gz
var packed []byte

// table is built once, on the first lookup that happens — which on a router
// that never opens the device list is never.
//
// Deferred rather than built in init() because the cost is real: ~1.3 MB held
// for the decompressed blob plus the map's own overhead, on a box that may
// have 512 MB and is also running unbound, dnsmasq and Caddy. A daemon that
// pays it at startup pays it on every box; a daemon that pays it on first use
// pays it on the boxes whose operator actually opened the screen.
//
// Keys and values are substrings of one backing string, so the entries cost no
// allocation of their own — only the map's.
var table = sync.OnceValue(load)

func load() map[string]string {
	zr, err := gzip.NewReader(bytes.NewReader(packed))
	if err != nil {
		// Unreachable short of a corrupted binary: the bytes are embedded at
		// build time and gen.go wrote them with this package's own gzip. An
		// empty table degrades to "no vendor known", which is a state every
		// caller already handles, so there is nothing to escalate to.
		return nil
	}
	defer zr.Close()

	raw, err := io.ReadAll(zr)
	if err != nil {
		return nil
	}

	m := make(map[string]string, bytes.Count(raw, []byte{'\n'})+1)
	for line := range strings.Lines(string(raw)) {
		line = strings.TrimSuffix(line, "\n")
		if line == "" || line[0] == '#' {
			continue
		}
		prefix, vendor, ok := strings.Cut(line, "\t")
		if !ok || vendor == "" {
			continue
		}
		m[prefix] = vendor
	}
	return m
}

// Vendor names the company that registered mac's prefix.
//
// It reports false rather than guessing, in three cases that are worth telling
// apart even though the caller treats them alike:
//
//   - The address is locally administered — a randomised MAC, which is now the
//     default on every major phone and laptop OS. There is no vendor to find:
//     the address was invented by the client minutes ago.
//   - The prefix is in no IEEE registry, or its holder asked not to be
//     published (those entries are listed as "Private" and gen.go drops them).
//   - The prefix falls in a subdivided MA-L block whose particular MA-S or
//     MA-M assignment is not registered. Answering with the parent block would
//     mean naming IEEE itself, so gen.go drops those parents too.
func Vendor(mac string) (string, bool) {
	prefixes, ok := core.OUIPrefixes(mac)
	if !ok {
		return "", false
	}
	m := table()
	// Longest first: an MA-S assignment is a different company from the MA-L
	// that contains it, and the specific one is the right answer.
	for _, p := range prefixes {
		if vendor, found := m[p]; found {
			return vendor, true
		}
	}
	return "", false
}

// Len reports how many prefixes the table holds. For tests, and for anyone
// wondering whether the generated file made it into the binary.
func Len() int { return len(table()) }

// Vendors returns every distinct name in the table, in no particular order.
//
// For tests, and the one it exists for earns the export: anything joining on a
// vendor *name* — the icon keys in internal/devices/vendor.go do — breaks
// silently the next time the generator's alias list is improved, and this is
// what turns that break into a build failure. It allocates a slice of thirty
// thousand strings, so it has no business in a request path.
func Vendors() []string {
	m := table()
	seen := make(map[string]struct{}, len(m)/2)
	out := make([]string, 0, len(m)/2)
	for _, vendor := range m {
		if _, dup := seen[vendor]; dup {
			continue
		}
		seen[vendor] = struct{}{}
		out = append(out, vendor)
	}
	return out
}
