package remote

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

// The Shadowsocks object: the one that lends a device this box's way out, and
// gives it no access to the network at all.
//
// It is worth being blunt about that, because the two objects in this module
// look interchangeable on a settings page and are not. A WireGuard peer is a
// device on a network at home and can reach the NAS. A Shadowsocks client can
// reach exactly what the internet can reach, from this box's address. They are
// not substitutes, and an operator may well want both: one to get *in*, one to
// borrow a route out from a network that is filtering or watching.
//
// Structurally it is the opposite of its neighbour in every way that matters to
// the code. WireGuard is kernel state with no daemon; this is a daemon with a
// rendered config file and a unit, which makes it shaped like internal/ingress.
// That contrast is the whole reason the two objects do not share a plan
// (config.go).

// DefaultShadowsocksPort is upstream's conventional port, and the one every
// guide tells an operator to forward.
const DefaultShadowsocksPort = 8388

// Shadowsocks is everything about the proxy.
type Shadowsocks struct {
	// Enabled controls whether the proxy runs at all. Disabling stops the
	// service and leaves the configuration in place, so it can be turned back
	// on without re-issuing anything.
	Enabled bool `json:"enabled"`

	// ListenPort is the TCP and UDP port this box listens on. Empty means
	// DefaultShadowsocksPort.
	ListenPort uint16 `json:"listen_port,omitempty"`

	// PublicPort is the port clients dial, when a router in front forwards a
	// different one to us. Empty — the ordinary case — means ListenPort.
	PublicPort uint16 `json:"public_port,omitempty"`

	// Cipher is how traffic is encrypted, and it decides what Password has to
	// be. Empty means DefaultCipher.
	Cipher Cipher `json:"cipher,omitempty"`

	// Password is the shared secret every client uses.
	//
	// Generated by olr rather than typed, and the reason is the trap in Cipher:
	// a 2022-blake3 cipher's "password" is not a passphrase at all, it is a
	// base64-encoded key of an exact length, and a human-chosen string is
	// rejected by the server with a message about base64 that gives no hint
	// that the *cipher* is what decided the format. Generating it means an
	// operator never meets that.
	//
	// Unlike WireGuard's key this one is redacted rather than hidden: a client
	// cannot be configured without it, so there is a route whose whole job is
	// to hand it over (ss_http.go). What it is kept out of is every surface
	// that prints configuration in passing.
	Password string `json:"password,omitempty" jsonschema:"description=Generated by olr. Redacted on config surfaces; the client route hands it over deliberately. Sending the mask back means 'unchanged'."`

	// UDP carries DNS and QUIC, and is on unless it is turned off.
	//
	// Off is upstream's default (`mode: tcp_only`) and is the wrong one here.
	// The symptom of a TCP-only proxy is not "UDP does not work" — it is "the
	// web works and some apps mysteriously do not", because name resolution and
	// anything over QUIC fall back slowly or not at all. olr renders
	// `tcp_and_udp` so nobody has to learn that; the field exists so that an
	// operator who wants the narrower thing can say so (design.md §5.6 —
	// declared, never inferred).
	UDP *bool `json:"udp,omitempty"`

	// ExtraConf is this object's declared escape hatch (design.md §3.2 rule 5):
	// merged into the rendered JSON, so any key shadowsocks-rust understands
	// and olr does not model can still be set.
	ExtraConf string `json:"raw_shadowsocks_conf,omitempty"`
}

// Cipher is a Shadowsocks encryption method.
type Cipher string

// The ciphers olr offers.
//
// Deliberately five rather than the twenty upstream accepts. The stream ciphers
// are broken and the older AEAD ones are on their way out; offering them would
// be offering an operator a way to make their proxy worse with no way to tell.
// docs/remote-access.md §12 records what was left out and why.
const (
	// Cipher2022AES128 is the default: SIP022, the current design, and the
	// cheapest of the three on a router's CPU.
	Cipher2022AES128 Cipher = "2022-blake3-aes-128-gcm"

	// Cipher2022AES256 is the same design with a longer key.
	Cipher2022AES256 Cipher = "2022-blake3-aes-256-gcm"

	// Cipher2022ChaCha is for hardware with no AES instructions — an older ARM
	// board, where ChaCha20 is several times faster than AES.
	Cipher2022ChaCha Cipher = "2022-blake3-chacha20-poly1305"

	// CipherAES256GCM is the previous generation, kept for one reason: a client
	// too old to speak SIP022. It takes an ordinary passphrase.
	CipherAES256GCM Cipher = "aes-256-gcm"

	// CipherChaCha20 is the same generation's ChaCha variant, kept for the same
	// reason.
	CipherChaCha20 Cipher = "chacha20-ietf-poly1305"
)

// DefaultCipher is what a config that does not choose gets.
const DefaultCipher = Cipher2022AES128

// Ciphers lists the vocabulary. One source, so the enum published in the schema
// and the check in the validator cannot disagree.
func Ciphers() []Cipher {
	return []Cipher{
		Cipher2022AES128, Cipher2022AES256, Cipher2022ChaCha,
		CipherAES256GCM, CipherChaCha20,
	}
}

// Valid reports whether c is a known cipher. The empty string is valid and
// means DefaultCipher.
func (c Cipher) Valid() bool { return c == "" || slices.Contains(Ciphers(), c) }

// OrDefault resolves the empty value.
func (c Cipher) OrDefault() Cipher {
	if c == "" {
		return DefaultCipher
	}
	return c
}

// KeyLen is the exact number of key bytes a SIP022 cipher's password must
// decode to, and zero for a cipher that takes an ordinary passphrase.
//
// **This is the trap this whole file exists to absorb.** For a `2022-blake3-…`
// method the password field is not a password: it is a base64-encoded
// pre-shared key of a length the cipher fixes, and a server handed anything
// else refuses to start with a complaint about base64 that never mentions the
// cipher. An operator who picks a stronger-sounding cipher and keeps their
// password gets a proxy that will not run, for a reason nothing on screen
// connects to what they changed.
//
// So olr generates the password *from* the cipher, and changing the cipher
// regenerates it (see Shadowsocks.WithGeneratedPassword).
func (c Cipher) KeyLen() int {
	switch c.OrDefault() {
	case Cipher2022AES128:
		return 16
	case Cipher2022AES256, Cipher2022ChaCha:
		return 32
	default:
		return 0
	}
}

// Keyed reports whether this cipher's password is a fixed-length key rather
// than a passphrase.
func (c Cipher) Keyed() bool { return c.KeyLen() > 0 }

// --- resolved defaults ------------------------------------------------------

// PortOrDefault resolves the zero listen port.
func (s Shadowsocks) PortOrDefault() uint16 {
	if s.ListenPort != 0 {
		return s.ListenPort
	}
	return DefaultShadowsocksPort
}

// DialPort is the port a client is told to use.
func (s Shadowsocks) DialPort() uint16 { return portOr(s.PublicPort, s.PortOrDefault()) }

// UDPEnabled resolves the nil pointer: on unless the operator said otherwise.
func (s Shadowsocks) UDPEnabled() bool { return s.UDP == nil || *s.UDP }

// --- the password -----------------------------------------------------------

// GeneratePassword returns a password of the shape a cipher requires.
//
// For a SIP022 cipher that is base64 of exactly KeyLen random bytes, which is
// the only thing the server will accept. For the older ciphers any string
// works, and 16 random bytes base64-encoded is a better one than a human would
// choose — this is a credential that is never typed from memory, so there is
// nothing to trade legibility for.
func GeneratePassword(c Cipher) (string, error) {
	n := c.KeyLen()
	if n == 0 {
		n = 16
	}
	raw := make([]byte, n)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generating a password: %w", err)
	}
	return base64.StdEncoding.EncodeToString(raw), nil
}

// WithGeneratedPassword fills in a password that is missing, or replaces one
// the cipher can no longer accept.
//
// The second half is the one worth stating. Changing a cipher between the two
// families changes what a password *is*, so keeping the old value would leave a
// server that refuses to start — the failure KeyLen describes. Regenerating is
// the only honest option, and it means every client has to be re-issued, which
// is why the plan classifies a cipher change as disruptive (ss_plan.go) rather
// than doing it quietly.
func (s Shadowsocks) WithGeneratedPassword() (Shadowsocks, bool, error) {
	if s.Password != "" && s.PasswordFitsCipher() == nil {
		return s, false, nil
	}
	password, err := GeneratePassword(s.Cipher)
	if err != nil {
		return s, false, err
	}
	out := s.Clone()
	out.Password = password
	return out, true, nil
}

// PasswordFitsCipher reports whether the stored password is one this cipher can
// use.
func (s Shadowsocks) PasswordFitsCipher() error {
	want := s.Cipher.KeyLen()
	if want == 0 {
		// Any non-empty string is a legal passphrase for the older ciphers.
		if strings.TrimSpace(s.Password) == "" {
			return fmt.Errorf("the password is empty")
		}
		return nil
	}
	raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(s.Password))
	if err != nil {
		return fmt.Errorf("%s needs a base64 key, and this is not base64", s.Cipher.OrDefault())
	}
	if len(raw) != want {
		return fmt.Errorf("%s needs a key of exactly %d bytes, and this one is %d",
			s.Cipher.OrDefault(), want, len(raw))
	}
	return nil
}

// --- canonical form ---------------------------------------------------------

// Normalize puts the proxy's config in canonical form.
func (s *Shadowsocks) Normalize() {
	s.Cipher = Cipher(strings.TrimSpace(strings.ToLower(string(s.Cipher))))
	s.Password = strings.TrimSpace(s.Password)
	// The password is trimmed but never re-cased: it is base64 or an opaque
	// passphrase, and altering it would produce a proxy nobody can connect to
	// with a diff that looks right.
}

// Clone deep-copies the proxy's config.
func (s Shadowsocks) Clone() Shadowsocks {
	out := s
	if s.UDP != nil {
		udp := *s.UDP
		out.UDP = &udp
	}
	return out
}

// Empty reports whether this object has been configured at all.
func (s Shadowsocks) Empty() bool {
	return !s.Enabled && s.Password == "" && s.Cipher == "" &&
		s.ListenPort == 0 && s.PublicPort == 0 && s.ExtraConf == ""
}

// UnmarshalShadowsocks parses the proxy's section, rejecting unknown fields.
//
// Strict for the reason UnmarshalConfig is: a typo'd key that is silently
// ignored produces a box quietly not doing what its config says — here, an
// operator who believes they turned UDP off and did not.
func UnmarshalShadowsocks(data []byte) (Shadowsocks, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var s Shadowsocks
	if err := dec.Decode(&s); err != nil {
		return Shadowsocks{}, fmt.Errorf("%s shadowsocks configuration: %w", ModuleName, err)
	}
	s.Normalize()
	return s, nil
}
