package remote

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

// The SOCKS5 object: the third and smallest of the three, and the only one that
// carries no encryption of its own.
//
// That last fact decides the whole shape of this file. SOCKS5 is a plaintext
// protocol — the credentials cross the network in the clear and so does every
// byte of what the client asked for. Beside it in this module sits a tunnel
// whose entire job is to encrypt exactly that. So the two are not rivals here,
// they compose: **the default is to listen only inside the WireGuard tunnel**,
// where the outer layer has already done the encrypting and a plain SOCKS5 port
// is a perfectly reasonable thing to run.
//
// The operator can still expose it to the internet, and olr does not refuse —
// but that is the one configuration that earns a warning, and the warning names
// what actually happens rather than saying "insecure". Listening on the tunnel
// is not a degraded mode to apologise for; it is the good one.
//
// Structurally this is Shadowsocks' twin rather than WireGuard's: a daemon with
// a rendered config file and a unit. The two proxies therefore share this
// module's file/service plan machinery (ss_plan.go's FileChange, ServiceAction,
// ProxyObserved, ProxyPlan) — shared because the *mechanism* is genuinely the
// same, not because the objects resemble each other. Their fields still overlap
// in nothing at all.

// DefaultSocksPort is the conventional SOCKS port, and what every client
// offers to fill in.
const DefaultSocksPort = 1080

// DefaultSocksUser is the account name olr creates when the operator does not
// pick one. A name is needed because 3proxy's `allow` rules are written against
// one; leaving it to the operator would make the common case a two-field form
// for no gain.
const DefaultSocksUser = "olr"

// Socks5 is everything about the plain SOCKS5 proxy.
type Socks5 struct {
	// Enabled controls whether the proxy runs at all. Disabling stops the
	// service and leaves the configuration in place, so it can be turned back
	// on without re-issuing credentials.
	Enabled bool `json:"enabled"`

	// ListenPort is the TCP port this box listens on. Empty means
	// DefaultSocksPort.
	ListenPort uint16 `json:"listen_port,omitempty"`

	// PublicPort is the port clients dial, when a router in front forwards a
	// different one to us. Empty — the ordinary case — means ListenPort.
	//
	// Only meaningful with ListenInternet: nothing forwards a port into a
	// WireGuard tunnel, so the validator refuses the combination rather than
	// letting it read as configured.
	PublicPort uint16 `json:"public_port,omitempty"`

	// Listen is where the proxy accepts connections, and it is the field this
	// object exists to get right. Empty means ListenTunnel.
	Listen ListenScope `json:"listen,omitempty"`

	// Username is the account clients authenticate as. Empty means
	// DefaultSocksUser.
	Username string `json:"username,omitempty"`

	// Password is the secret clients authenticate with.
	//
	// Generated by olr rather than typed, for the same reason Shadowsocks'
	// is — it is a credential nobody types from memory, so there is nothing to
	// trade legibility for — and redacted rather than hidden, because a client
	// cannot be configured without it. The route that hands it over is the one
	// whose whole job is handing it over (socks_http.go).
	Password string `json:"password,omitempty" jsonschema:"description=Generated by olr. Redacted on config surfaces; the client route hands it over deliberately. Sending the mask back means 'unchanged'."`

	// ExtraConf is this object's declared escape hatch (design.md §3.2 rule 5):
	// lines appended to the rendered 3proxy configuration, for anything 3proxy
	// understands and olr does not model.
	//
	// It carries more weight here than in the object next door, because one
	// thing olr deliberately does not render is a UDP flag — see
	// socks_render.go, which explains what is unverified and why guessing would
	// have been worse than leaving it out.
	ExtraConf string `json:"raw_3proxy_conf,omitempty"`
}

// ListenScope is where the proxy accepts connections.
type ListenScope string

const (
	// ListenTunnel binds the proxy to this box's address inside the WireGuard
	// tunnel, so only a dialled-in peer can reach it.
	//
	// The default, and the one that makes a plaintext protocol a reasonable
	// thing to run: WireGuard has already authenticated the peer and encrypted
	// the path, so SOCKS5 is carrying cleartext inside a tunnel rather than
	// across the internet.
	//
	// It depends on the tunnel being configured, which is a real coupling and
	// is checked: ValidateSocks refuses this scope when WireGuard is disabled
	// or has no address, because the alternative is a proxy that binds nothing
	// and reports itself as running.
	ListenTunnel ListenScope = "tunnel"

	// ListenInternet binds the proxy to every interface, so anything that can
	// route to this box can reach it.
	//
	// Available, never the default, and never silent — the same treatment
	// gateway gives its `direct` failure mode. SocksExposureWarning is the text,
	// and it is attached to *this value* rather than to the object, because a
	// tunnel-scoped proxy has nothing to warn about and an operator who sees a
	// warning every time learns to scroll past it.
	ListenInternet ListenScope = "internet"
)

// ListenScopes lists the vocabulary. One source, so the enum published in the
// schema and the check in the validator cannot disagree.
func ListenScopes() []ListenScope { return []ListenScope{ListenTunnel, ListenInternet} }

// Valid reports whether s is a known scope. The empty string is valid and means
// ListenTunnel.
func (s ListenScope) Valid() bool { return s == "" || slices.Contains(ListenScopes(), s) }

// OrDefault resolves the empty value.
func (s ListenScope) OrDefault() ListenScope {
	if s == "" {
		return ListenTunnel
	}
	return s
}

// Exposed reports whether this scope puts the proxy where the internet can
// reach it.
func (s ListenScope) Exposed() bool { return s.OrDefault() == ListenInternet }

// SocksExposureWarning is what an operator is told when they expose a plaintext
// proxy, and it is written to be acted on rather than dismissed.
//
// Three specific consequences and then the remedy, because "SOCKS5 is not
// encrypted" is a fact an operator can read and still not connect to their own
// situation. The remedy line is the point: this module already contains the
// thing that fixes it, so the warning is one setting away from being moot.
//
// Deliberately a warning and not a refusal. design.md §5.6 draws that line at
// whether olr can know the operator is wrong, and here it cannot: a proxy
// exposed to a trusted private WAN, or reached only through someone else's VPN,
// is a legitimate configuration. The user's instruction when this was decided
// was exactly that — hint, and let them decide.
const SocksExposureWarning = "SOCKS5 sends credentials and traffic in the clear, " +
	"so exposing it to the internet means: the username and password cross every " +
	"network in between as plaintext; anyone on the path sees which sites are " +
	"visited; and open proxy ports are found by scanners within hours and used by " +
	"strangers. Setting `listen` to `tunnel` puts it inside WireGuard instead, " +
	"which encrypts all three away."

// --- resolved defaults ------------------------------------------------------

// PortOrDefault resolves the zero listen port.
func (s Socks5) PortOrDefault() uint16 {
	if s.ListenPort != 0 {
		return s.ListenPort
	}
	return DefaultSocksPort
}

// DialPort is the port a client is told to use.
func (s Socks5) DialPort() uint16 { return portOr(s.PublicPort, s.PortOrDefault()) }

// UserOrDefault resolves the empty username.
func (s Socks5) UserOrDefault() string {
	if u := strings.TrimSpace(s.Username); u != "" {
		return u
	}
	return DefaultSocksUser
}

// ListenScopeOrDefault resolves the empty scope.
func (s Socks5) ListenScopeOrDefault() ListenScope { return s.Listen.OrDefault() }

// --- the password -----------------------------------------------------------

// GenerateSocksPassword returns a password for the proxy.
//
// 16 random bytes, base64. Unlike Shadowsocks there is no cipher dictating a
// length here — any string is a legal SOCKS5 password — so this is simply a
// better secret than a human would pick for something they never type.
//
// One constraint the encoding has to respect and does: 3proxy's configuration
// is line- and space-delimited, and a `users` line is `name:TYPE:secret`. Base64
// contains no whitespace and no colon, so the rendered line cannot be split in
// the wrong place by a password. That is why this is not, say, a passphrase.
func GenerateSocksPassword() (string, error) {
	raw := make([]byte, 16)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generating a password: %w", err)
	}
	return base64.StdEncoding.EncodeToString(raw), nil
}

// WithGeneratedPassword fills in a password that is missing.
//
// Simpler than its Shadowsocks counterpart, and the difference is worth stating
// because the asymmetry looks like an oversight: there, changing the cipher
// changes what a password *is*, so an existing one can stop being usable and
// has to be replaced. Here nothing about the rest of the config can invalidate a
// password, so one that exists is kept — which means changing the port or the
// listen scope does not re-issue credentials to anybody.
func (s Socks5) WithGeneratedPassword() (Socks5, bool, error) {
	if strings.TrimSpace(s.Password) != "" {
		return s, false, nil
	}
	password, err := GenerateSocksPassword()
	if err != nil {
		return s, false, err
	}
	out := s.Clone()
	out.Password = password
	return out, true, nil
}

// --- canonical form ---------------------------------------------------------

// Normalize puts the proxy's config in canonical form.
func (s *Socks5) Normalize() {
	s.Listen = ListenScope(strings.TrimSpace(strings.ToLower(string(s.Listen))))
	s.Username = strings.TrimSpace(s.Username)
	s.Password = strings.TrimSpace(s.Password)
	// The password is trimmed but never re-cased: it is base64, and altering it
	// would produce a proxy nobody can authenticate against with a diff that
	// looks perfectly correct.
	s.ExtraConf = strings.TrimRight(s.ExtraConf, "\n\t ")
}

// Clone deep-copies the proxy's config.
//
// No pointer or slice fields today, so this is a plain copy — written out
// anyway because the two objects beside it have one and a future field that
// needs deep copying must not be the thing that discovers this method missing.
func (s Socks5) Clone() Socks5 { return s }

// Empty reports whether this object has been configured at all.
func (s Socks5) Empty() bool {
	return !s.Enabled && s.Password == "" && s.Username == "" && s.Listen == "" &&
		s.ListenPort == 0 && s.PublicPort == 0 && s.ExtraConf == ""
}

// UnmarshalSocks parses the proxy's section, rejecting unknown fields.
//
// Strict for the reason UnmarshalConfig is: a typo'd key that is silently
// ignored produces a box quietly not doing what its config says — here, an
// operator who believes they confined the proxy to the tunnel and did not,
// which is the one mistake in this object that matters.
func UnmarshalSocks(data []byte) (Socks5, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var s Socks5
	if err := dec.Decode(&s); err != nil {
		return Socks5{}, fmt.Errorf("%s socks5 configuration: %w", ModuleName, err)
	}
	s.Normalize()
	return s, nil
}
