package remote

import (
	"encoding/json"
	"strings"
)

// The proxy's rules. Pure — no files, no network, no root — so the whole set is
// table-tested and `olr remote` can check a config on a laptop.
//
// There is less here than next door, and the difference is the object rather
// than the effort: a Shadowsocks server is one port, one cipher and one secret,
// with no addresses to allocate and no second network to overlap with. What it
// does have is one coupling sharp enough to be worth most of this file — the
// password's shape is decided by the cipher (Cipher.KeyLen).

// ValidateShadowsocks checks the proxy's half of a config.
func ValidateShadowsocks(c Config) Result {
	var r Result
	s := c.Shadowsocks

	if !s.Cipher.Valid() {
		r.errorf("shadowsocks.cipher", "unknown cipher %q (want %s)", s.Cipher, joinCiphers())
	}

	if s.ListenPort != 0 && s.ListenPort < 1024 {
		// Not refused: olr runs as root and the kernel will allow it. Worth a
		// remark because a low port is far more likely to be a typo than a
		// choice, and because some networks treat the range differently.
		r.warnf("shadowsocks.listen_port",
			"%d is a privileged port; upstream's default is %d and nothing here needs a low one",
			s.ListenPort, DefaultShadowsocksPort)
	}
	if s.ListenPort != 0 && s.ListenPort == c.WireGuard.PortOrDefault() {
		// One is UDP and the other is TCP and UDP, so they would genuinely
		// collide — and the failure is a unit that will not start, reported one
		// layer away from the field that caused it.
		r.errorf("shadowsocks.listen_port",
			"%d is already the tunnel's port, and both listen on UDP", s.ListenPort)
	}

	if s.Enabled {
		switch {
		case s.Password == "":
			// Reached only by a config edited by hand or restored with the
			// secret stripped: every path that enables the proxy through olr
			// generates one first.
			r.errorf("shadowsocks.password",
				"this box has no password yet. `olr remote enable shadowsocks` generates one")
		default:
			if err := s.PasswordFitsCipher(); err != nil {
				// The trap, reported against the field that actually decides
				// it. Saying "the password is wrong" would send an operator to
				// change the password when what they changed was the cipher.
				r.errorf("shadowsocks.password",
					"%v. olr generates a password that fits the cipher — changing the cipher "+
						"regenerates it, and every client has to be given the new one", err)
			}
		}
	}

	validateShadowsocksExtra(&r, s.ExtraConf)
	return r
}

// ownedKeys are the settings this object renders itself.
//
// The escape hatch is a JSON merge rather than an append (ss_render.go), which
// means it *can* overwrite a key olr rendered — unlike the Caddyfile hatch next
// door, where a duplicate directive is merely additional. So the check here is
// load-bearing rather than tidy: without it the stored config and the file the
// daemon reads could disagree about the port, and every surface in olr would
// report the stored one.
var ownedKeys = map[string]string{
	"server_port": "set from shadowsocks.listen_port",
	"password":    "generated by olr and stored in the configuration",
	"method":      "set from shadowsocks.cipher",
	"mode":        "set from shadowsocks.udp",
}

func validateShadowsocksExtra(r *Result, extra string) {
	extra = strings.TrimSpace(extra)
	if extra == "" {
		return
	}

	var fields map[string]json.RawMessage
	if err := json.Unmarshal([]byte(extra), &fields); err != nil {
		r.errorf("shadowsocks.raw_shadowsocks_conf",
			"this has to be a JSON object, so that olr can merge it into the rendered "+
				"configuration: %v", err)
		return
	}
	for key := range fields {
		if why, owned := ownedKeys[strings.ToLower(key)]; owned {
			r.errorf("shadowsocks.raw_shadowsocks_conf",
				"%q is rendered by this module: %s", key, why)
		}
	}
}

func joinCiphers() string {
	out := make([]string, 0, len(Ciphers()))
	for _, c := range Ciphers() {
		out = append(out, string(c))
	}
	return strings.Join(out, ", ")
}
