package remote

import (
	"crypto/ecdh"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
)

// Key pairs, in the standard library.
//
// A WireGuard key is 32 bytes of X25519, base64-encoded. `wg genkey` and
// `wg pubkey` produce them, and running those would have been the obvious thing
// — this module already runs `wg` (kernel.go).
//
// It is done here instead for one reason: key generation is the only operation
// in this module that has to work on a machine with no `wg` and no Linux,
// because that is where the tests run. crypto/ecdh makes the whole of key
// handling pure, testable anywhere, independent of whether the backend is
// installed, and free of a dependency — `go.mod` has six direct entries and
// that restraint has already decided several arguments in this codebase.
//
// A key generated here and a key generated by `wg genkey` are indistinguishable:
// the clamping below is the same clamping, so the same random bytes produce the
// same pair either way.

// KeyLen is the length of a WireGuard key in bytes, before base64.
const KeyLen = 32

// KeyPair is both halves of a key, base64 as WireGuard spells them.
type KeyPair struct {
	// Private is the half that never leaves the box it belongs to. For a peer
	// it is returned exactly once, in the client configuration, and stored
	// nowhere (docs/remote-access.md §4.1).
	Private string

	// Public is the half that goes in the other side's configuration.
	Public string
}

// ErrBadKey reports a value that is not a WireGuard key.
var ErrBadKey = errors.New("not a WireGuard key")

// GenerateKey returns a new key pair.
func GenerateKey() (KeyPair, error) {
	var raw [KeyLen]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return KeyPair{}, fmt.Errorf("generating a key: %w", err)
	}
	clamp(&raw)

	public, err := publicFor(raw[:])
	if err != nil {
		return KeyPair{}, err
	}
	return KeyPair{
		Private: base64.StdEncoding.EncodeToString(raw[:]),
		Public:  public,
	}, nil
}

// clamp is RFC 7748's scalar clamping, applied at generation time.
//
// X25519 clamps internally on every use, so an unclamped private key would
// still produce the right public key and still work. It is done here anyway so
// that the bytes olr stores are the bytes `wg genkey` would have stored — an
// operator comparing the two should not find a difference to explain.
func clamp(k *[KeyLen]byte) {
	k[0] &= 248
	k[31] &= 127
	k[31] |= 64
}

// PublicKeyFor derives the public half of a stored private key.
//
// Derived on demand rather than stored beside the private half. There is
// exactly one source for the pair that way, so the public key in a client
// configuration cannot be a stale copy of a key the box has since replaced —
// which would present as a tunnel that never completes a handshake, with both
// files looking correct.
func PublicKeyFor(private string) (string, error) {
	raw, err := decodeKey(private)
	if err != nil {
		return "", err
	}
	return publicFor(raw)
}

func publicFor(raw []byte) (string, error) {
	key, err := ecdh.X25519().NewPrivateKey(raw)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrBadKey, err)
	}
	return base64.StdEncoding.EncodeToString(key.PublicKey().Bytes()), nil
}

// ValidKey reports whether s is a well-formed WireGuard key.
//
// Length is the check that matters and the one an operator trips: a truncated
// paste is still valid base64, and `wg setconf` rejects it with a line number
// rather than a name. Checking here means the refusal says which peer.
func ValidKey(s string) error {
	_, err := decodeKey(s)
	return err
}

func decodeKey(s string) ([]byte, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return nil, fmt.Errorf("%w: it is empty", ErrBadKey)
	}
	raw, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		return nil, fmt.Errorf("%w: it is not base64", ErrBadKey)
	}
	if len(raw) != KeyLen {
		return nil, fmt.Errorf("%w: it decodes to %d bytes, not %d", ErrBadKey, len(raw), KeyLen)
	}
	return raw, nil
}
