package dhcp

import (
	"flag"
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite the golden files in testdata")

// renderGolden renders a config and compares the whole file set against a
// golden file.
//
// Golden files rather than assertions on substrings: the rendered config is the
// module's actual contract with dnsmasq, and a diff against a reviewed file is
// the only check that notices a line nobody thought to assert on disappearing.
func renderGolden(t *testing.T, name string, c Config, links LinkView) {
	t.Helper()

	rendered, err := NewDnsmasq(DefaultPaths()).Render(c, links)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	var got strings.Builder
	for _, f := range rendered.Files {
		fmt.Fprintf(&got, "=== %s (mode %04o, reloadable=%v)\n", f.Path, f.Mode, f.Reloadable)
		got.Write(f.Data)
	}

	golden := filepath.Join("testdata", name+".txt")
	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, []byte(got.String()), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}

	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("%v\n\nrun `go test ./internal/dhcp -update` to create it. Rendered:\n%s", err, got.String())
	}
	if got.String() != string(want) {
		change := Change{Path: golden, Kind: ChangeUpdate, Before: want, After: []byte(got.String())}
		t.Errorf("rendered output does not match %s:\n%s", golden, change.Diff())
	}
}

func TestRenderMinimalPool(t *testing.T) {
	renderGolden(t, "minimal", validConfig(t), testLinks())
}

func TestRenderEverything(t *testing.T) {
	gw := addr(t, "192.168.1.254")
	lease, err := ParseDuration("6h")
	if err != nil {
		t.Fatal(err)
	}

	c := validConfig(t)
	c.Pools[0].LeaseTime = lease
	c.Pools[0].Gateway = &gw
	c.Pools[0].DNS = []netip.Addr{addr(t, "192.168.1.1"), addr(t, "2001:db8::1")}
	c.Pools[0].Domain = "lan"
	c.Pools[0].NTP = []netip.Addr{addr(t, "192.168.1.1")}
	c.Pools[0].RA = RASLAAC
	c.Pools[0].Options = []Option{{Option: "252", Value: "http://wpad.lan/wpad.dat"}}
	c.Reservations = []Reservation{
		{MAC: "aa:bb:cc:dd:ee:ff", IP: addr(t, "192.168.1.50"), Hostname: "nas"},
		{MAC: "11:22:33:44:55:66", IP: addr(t, "192.168.1.51"), LeaseTime: Duration(0)},
	}
	c.ExtraConf = "log-dhcp\ndhcp-authoritative"

	renderGolden(t, "everything", c, testLinks())
}

func TestRenderStatefulIPv6(t *testing.T) {
	c := validConfig(t)
	c.Pools[0].RA = RAStateful
	renderGolden(t, "stateful-v6", c, testLinks())
}

func TestRenderTwoPools(t *testing.T) {
	c := validConfig(t)
	c.Pools = append(c.Pools, Pool{
		Interface: "br-guest",
		Start:     addr(t, "10.10.0.100"),
		End:       addr(t, "10.10.0.200"),
		Domain:    "guest",
		RA:        RASLAAC,
	})
	renderGolden(t, "two-pools", c, testLinks())
}

// Disabling stops the service but still renders, so that enabling later is a
// plain start rather than a re-render.
func TestRenderDisabled(t *testing.T) {
	c := validConfig(t)
	c.Enabled = false
	renderGolden(t, "disabled", c, testLinks())
}

// port=0 is the obligation dnsmasq's dual role creates: without it this daemon
// silently becomes a second resolver and breaks the one-daemon-one-owner rule
// (design.md §4.2). Asserted separately from the golden files because a golden
// file can be regenerated by accident and this must never change.
func TestRenderAlwaysDisablesDNS(t *testing.T) {
	for _, name := range []string{"enabled", "disabled"} {
		c := validConfig(t)
		c.Enabled = name == "enabled"

		rendered, err := NewDnsmasq(DefaultPaths()).Render(c, testLinks())
		if err != nil {
			t.Fatal(err)
		}
		conf, ok := rendered.Get(DefaultPaths().Conf)
		if !ok {
			t.Fatal("no main config rendered")
		}
		if !hasDirective(string(conf.Data), "port=0") {
			t.Errorf("%s config does not set port=0:\n%s", name, conf.Data)
		}
	}
}

// Rendering must be a pure function of the config, or drift detection — which
// compares rendered bytes against the disk — would report changes that are not
// changes.
func TestRenderIsDeterministic(t *testing.T) {
	c := validConfig(t)
	c.Reservations = []Reservation{
		{MAC: "ff:ee:dd:cc:bb:aa", IP: addr(t, "192.168.1.52")},
		{MAC: "aa:bb:cc:dd:ee:ff", IP: addr(t, "192.168.1.50")},
	}
	c.Pools = append(c.Pools, Pool{
		Interface: "br-guest", Start: addr(t, "10.10.0.100"), End: addr(t, "10.10.0.200"),
	})

	shuffled := c.Clone()
	shuffled.Reservations[0], shuffled.Reservations[1] = shuffled.Reservations[1], shuffled.Reservations[0]
	shuffled.Pools[0], shuffled.Pools[1] = shuffled.Pools[1], shuffled.Pools[0]

	b := NewDnsmasq(DefaultPaths())
	first, err := b.Render(c, testLinks())
	if err != nil {
		t.Fatal(err)
	}
	second, err := b.Render(shuffled, testLinks())
	if err != nil {
		t.Fatal(err)
	}

	if len(first.Files) != len(second.Files) {
		t.Fatalf("file counts differ: %d vs %d", len(first.Files), len(second.Files))
	}
	for i := range first.Files {
		if first.Files[i].Path != second.Files[i].Path {
			t.Errorf("file %d: %s vs %s", i, first.Files[i].Path, second.Files[i].Path)
			continue
		}
		if string(first.Files[i].Data) != string(second.Files[i].Data) {
			t.Errorf("%s differs after reordering the config", first.Files[i].Path)
		}
	}
}

// The reloadable split is what makes adding a reservation a reload rather than
// a restart, so it is asserted rather than left implicit in the golden files.
func TestReloadableFilesAreTheHotOnes(t *testing.T) {
	c := validConfig(t)
	c.Pools[0].Domain = "lan"
	c.Reservations = []Reservation{{MAC: "aa:bb:cc:dd:ee:ff", IP: addr(t, "192.168.1.50")}}

	paths := DefaultPaths()
	rendered, err := NewDnsmasq(paths).Render(c, testLinks())
	if err != nil {
		t.Fatal(err)
	}

	for _, f := range rendered.Files {
		inHotDir := strings.HasPrefix(f.Path, paths.HostsDir+"/") || strings.HasPrefix(f.Path, paths.OptsDir+"/")
		if f.Reloadable != inHotDir {
			t.Errorf("%s: Reloadable=%v but it %s in a SIGHUP-reread directory",
				f.Path, f.Reloadable, map[bool]string{true: "is", false: "is not"}[inHotDir])
		}
	}
	if _, ok := rendered.Get(paths.HostsDir + "/aabbccddeeff.conf"); !ok {
		t.Errorf("no per-reservation file; got %v", rendered.Paths())
	}
}

func TestNetmaskOf(t *testing.T) {
	tests := []struct{ prefix, want string }{
		{"192.168.1.1/24", "255.255.255.0"},
		{"10.0.0.1/8", "255.0.0.0"},
		{"172.16.0.1/12", "255.240.0.0"},
		{"192.168.1.1/30", "255.255.255.252"},
		{"192.168.1.1/32", "255.255.255.255"},
		{"0.0.0.0/0", "0.0.0.0"},
	}
	for _, tc := range tests {
		if got := netmaskOf(netip.MustParsePrefix(tc.prefix)); got != tc.want {
			t.Errorf("netmaskOf(%s) = %q, want %q", tc.prefix, got, tc.want)
		}
	}
}

// TestDnsmasqAcceptsRenderedConfig runs dnsmasq's own parser over everything we
// generate. Our golden files prove we render what we meant to; only dnsmasq can
// prove that what we meant to render is legal.
//
// Skipped where dnsmasq is not installed, which includes the dev container —
// this is one of the checks that only becomes real on the target box.
func TestDnsmasqAcceptsRenderedConfig(t *testing.T) {
	bin, err := exec.LookPath("dnsmasq")
	if err != nil {
		t.Skip("dnsmasq not installed; run this on a box that has it")
	}

	configs := map[string]func(*testing.T) Config{
		"minimal": validConfig,
		"stateful-v6": func(t *testing.T) Config {
			c := validConfig(t)
			c.Pools[0].RA = RAStateful
			return c
		},
		"everything": func(t *testing.T) Config {
			gw := addr(t, "192.168.1.254")
			c := validConfig(t)
			c.Pools[0].Gateway = &gw
			c.Pools[0].DNS = []netip.Addr{addr(t, "192.168.1.1"), addr(t, "2001:db8::1")}
			c.Pools[0].Domain = "lan"
			c.Pools[0].NTP = []netip.Addr{addr(t, "192.168.1.1")}
			c.Pools[0].RA = RASLAAC
			c.Pools[0].Options = []Option{{Option: "252", Value: "http://wpad.lan/wpad.dat"}}
			c.Reservations = []Reservation{{MAC: "aa:bb:cc:dd:ee:ff", IP: addr(t, "192.168.1.50"), Hostname: "nas"}}
			c.ExtraConf = "log-dhcp"
			return c
		},
	}

	for name, build := range configs {
		t.Run(name, func(t *testing.T) {
			root := t.TempDir()
			paths := Paths{
				Conf:      filepath.Join(root, "dnsmasq.conf"),
				HostsDir:  filepath.Join(root, "hosts.d"),
				OptsDir:   filepath.Join(root, "opts.d"),
				LeaseFile: filepath.Join(root, "leases"),
				PIDFile:   filepath.Join(root, "dhcp.pid"),
			}
			for _, dir := range []string{paths.HostsDir, paths.OptsDir} {
				if err := os.MkdirAll(dir, 0o755); err != nil {
					t.Fatal(err)
				}
			}

			rendered, err := NewDnsmasq(paths).Render(build(t), testLinks())
			if err != nil {
				t.Fatal(err)
			}
			for _, f := range rendered.Files {
				if err := os.MkdirAll(filepath.Dir(f.Path), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(f.Path, f.Data, f.Mode); err != nil {
					t.Fatal(err)
				}
			}

			out, err := exec.Command(bin, "--test", "-C", paths.Conf).CombinedOutput()
			if err != nil {
				t.Errorf("dnsmasq rejected the rendered config: %v\n%s", err, out)
			}
		})
	}
}

// hasDirective reports whether a config sets a directive, ignoring comments.
func hasDirective(conf, directive string) bool {
	for _, line := range strings.Split(conf, "\n") {
		if strings.TrimSpace(line) == directive {
			return true
		}
	}
	return false
}
