package host

import (
	"context"
	"net/netip"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"syscall"
	"testing"
)

// Debian 13's /etc/dhcpcd.conf as shipped, abridged — including an `interface`
// block of the operator's own, which is what makes the file positional.
const stockDhcpcd = `# A sample configuration for dhcpcd.
hostname
duid
persistent
vendorclassid
option domain_name_servers, domain_name, domain_search
require dhcp_server_identifier
slaac private

interface eth9
	static ip_address=10.0.0.2/24
`

const dhcpcdResolv = `# Generated by dhcpcd
search home.arpa
# /etc/resolv.conf.head can replace this line
nameserver 10.9.9.9
options edns0
# /etc/resolv.conf.tail can replace this line
`

var uplinkDNS = []netip.Addr{netip.MustParseAddr("192.168.1.1")}

func TestDhcpcdBlocksRoundTrip(t *testing.T) {
	d := Desired{IPv4: []string{"ens18", "ens19", "ens18"}, Resolvers: uplinkDNS}
	got := renderDhcpcd(stockDhcpcd, d)

	if !strings.HasPrefix(got, blockBegin) || !strings.Contains(got[:200], "nohook resolv.conf") {
		t.Errorf("the global option is not at the top, where it applies to every interface:\n%s", got)
	}
	tail := got[strings.LastIndex(got, blockBegin):]
	if !strings.Contains(tail, "interface ens18\n\tipv6only\ninterface ens19\n\tipv6only\n") {
		t.Errorf("the interface block is wrong or not last:\n%s", tail)
	}
	if again := renderDhcpcd(got, d); again != got {
		t.Errorf("rendering twice changed the file:\n%s", again)
	}
	if back := renderDhcpcd(got, Desired{}); back != stockDhcpcd {
		t.Errorf("giving back did not restore the file exactly:\n%q\nwant\n%q", back, stockDhcpcd)
	}
	if same := renderDhcpcd(stockDhcpcd, Desired{}); same != stockDhcpcd {
		t.Error("a file olr never touched was changed")
	}
}

// A begin marker whose end was deleted by hand must not swallow the rest of
// somebody's file.
func TestAnUnterminatedBlockIsLeftAlone(t *testing.T) {
	conf := stockDhcpcd + blockBegin + ": half deleted\ninterface ens18\n\tipv6only\nhostname\n"
	if got := stripBlocks(conf); got != conf {
		t.Errorf("stripBlocks ate an unterminated block:\n%s", got)
	}
}

func TestResolvConfKeepsTheOperatorsSearchAndOptions(t *testing.T) {
	got := renderResolvConf(dhcpcdResolv, uplinkDNS)
	want := resolvHeader + "search home.arpa\nnameserver 192.168.1.1\noptions edns0\n"
	if got != want {
		t.Errorf("renderResolvConf =\n%s\nwant\n%s", got, want)
	}
}

// --- against a fake root -----------------------------------------------------

type box struct {
	t       *testing.T
	root    string
	signals []int
	restart []string
}

func newBox(t *testing.T) *box {
	b := &box{t: t, root: t.TempDir()}
	b.write("/etc/dhcpcd.conf", stockDhcpcd)
	b.write("/run/dhcpcd/ens18.pid", "698\n")
	b.write("/proc/698/comm", "dhcpcd\n")
	b.write("/etc/resolv.conf", dhcpcdResolv)
	return b
}

func (b *box) write(p, content string) {
	b.t.Helper()
	full := filepath.Join(b.root, p)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		b.t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		b.t.Fatal(err)
	}
}

func (b *box) read(p string) string {
	b.t.Helper()
	data, err := os.ReadFile(filepath.Join(b.root, p))
	if err != nil {
		return ""
	}
	return string(data)
}

func (b *box) applier() Applier {
	return Applier{
		Root:    b.root,
		Signal:  func(pid int, _ Sig) error { b.signals = append(b.signals, pid); return nil },
		Restart: func(_ context.Context, unit string) error { b.restart = append(b.restart, unit); return nil },
		Index:   func(string) (int, error) { return 2, nil },
	}
}

// The box this was built for: dhcpcd on the uplink, writing resolv.conf.
func TestTakingOverFromDhcpcdAndGivingBack(t *testing.T) {
	b := newBox(t)
	a := b.applier()
	ctx := context.Background()
	d := Desired{IPv4: []string{"ens18"}, Resolvers: uplinkDNS}

	if _, err := a.Apply(ctx, d); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(b.read("/etc/dhcpcd.conf"), "interface ens18\n\tipv6only") {
		t.Errorf("dhcpcd was not told:\n%s", b.read("/etc/dhcpcd.conf"))
	}
	if !slices.Equal(b.signals, []int{698}) {
		t.Errorf("signalled %v, want dhcpcd's pid once", b.signals)
	}
	if got := a.Resolvers(); !slices.Equal(got, uplinkDNS) {
		t.Errorf("the box resolves through %v, want %v", got, uplinkDNS)
	}

	// Idempotent: a second apply, as at every olrd start, touches nothing.
	b.signals = nil
	steps, err := a.Apply(ctx, d)
	if err != nil || len(steps) != 0 || len(b.signals) != 0 {
		t.Errorf("a second apply did work: steps %+v, signals %v, err %v", steps, b.signals, err)
	}

	// Giving back: both files as they were, and dhcpcd told again.
	if _, err := a.Apply(ctx, Desired{}); err != nil {
		t.Fatal(err)
	}
	if got := b.read("/etc/dhcpcd.conf"); got != stockDhcpcd {
		t.Errorf("dhcpcd.conf was not given back exactly:\n%s", got)
	}
	if got := b.read("/etc/resolv.conf"); got != dhcpcdResolv {
		t.Errorf("resolv.conf was not put back:\n%s", got)
	}
	if len(b.signals) != 1 {
		t.Errorf("dhcpcd was not told about the give-back: %v", b.signals)
	}
}

// A pidfile that outlived its process names somebody else's pid by now.
func TestAStalePidfileIsNeverSignalled(t *testing.T) {
	b := newBox(t)
	b.write("/proc/698/comm", "bash\n")
	a := b.applier()
	if _, err := a.Apply(context.Background(), Desired{IPv4: []string{"ens18"}}); err != nil {
		t.Fatal(err)
	}
	if len(b.signals) != 0 {
		t.Errorf("signalled %v, whose comm is not dhcpcd", b.signals)
	}
}

func TestSystemdResolvedGetsADropInAndKeepsItsLink(t *testing.T) {
	b := newBox(t)
	if err := os.Remove(filepath.Join(b.root, "/etc/resolv.conf")); err != nil {
		t.Fatal(err)
	}
	b.write("/run/systemd/resolve/stub-resolv.conf", "nameserver 127.0.0.53\n")
	if err := os.Symlink("../run/systemd/resolve/stub-resolv.conf", filepath.Join(b.root, "/etc/resolv.conf")); err != nil {
		t.Fatal(err)
	}
	a := b.applier()
	ctx := context.Background()

	if _, err := a.Apply(ctx, Desired{Resolvers: uplinkDNS}); err != nil {
		t.Fatal(err)
	}
	if got := b.read(resolvedDropIn); !strings.Contains(got, "[Resolve]\nDNS=192.168.1.1\n") {
		t.Errorf("drop-in = %q", got)
	}
	if fi, _ := os.Lstat(filepath.Join(b.root, "/etc/resolv.conf")); fi.Mode()&os.ModeSymlink == 0 {
		t.Error("the link into resolved was replaced")
	}
	if !slices.Equal(b.restart, []string{resolvedUnit}) {
		t.Errorf("restarted %v", b.restart)
	}

	if _, err := a.Apply(ctx, Desired{}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(b.root, resolvedDropIn)); !os.IsNotExist(err) {
		t.Error("the drop-in outlived the resolvers")
	}
}

// A link to anything but resolved belongs to a program olr does not drive yet:
// said, not changed.
func TestAnUnknownResolvConfLinkIsReportedNotReplaced(t *testing.T) {
	b := newBox(t)
	if err := os.Remove(filepath.Join(b.root, "/etc/resolv.conf")); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("/run/resolvconf/resolv.conf", filepath.Join(b.root, "/etc/resolv.conf")); err != nil {
		t.Fatal(err)
	}
	a := b.applier()
	d := Desired{Resolvers: uplinkDNS}
	if _, err := a.Apply(context.Background(), d); err != nil {
		t.Fatal(err)
	}
	if target, _ := os.Readlink(filepath.Join(b.root, "/etc/resolv.conf")); target != "/run/resolvconf/resolv.conf" {
		t.Errorf("the link now points at %q", target)
	}
	if f := a.Findings(d); len(f) != 1 || !strings.Contains(f[0].Message, "/run/resolvconf/resolv.conf") {
		t.Errorf("findings = %+v", f)
	}
}

func TestTheManagersOlrDoesNotTakeOverAreNamed(t *testing.T) {
	b := newBox(t)
	b.write("/run/systemd/netif/links/2", "ADMIN_STATE=configured\nOPER_STATE=routable\n")
	b.write("/run/NetworkManager/devices/2", "[device]\nmanaged=true\n")
	b.write("/proc/900/cmdline", "/sbin/dhclient\x00-4\x00-v\x00ens18\x00")
	a := b.applier()

	var got []string
	for _, f := range a.Findings(Desired{IPv4: []string{"ens18"}}) {
		got = append(got, strings.SplitN(f.Message, " ", 2)[0])
	}
	if !slices.Equal(got, []string{"systemd-networkd", "NetworkManager", "dhclient"}) {
		t.Errorf("findings named %v", got)
	}
}

// Pinned because getting it wrong is silent until it is not: SIGALRM is
// dhcpcd's --release, which stops it and de-configures the interface, IPv6
// and all. It is what the first version sent.
func TestReloadIsDhcpcdsRebindNotItsRelease(t *testing.T) {
	got, err := sysSignal(SigReload)
	if err != nil || got != syscall.SIGHUP {
		t.Fatalf("SigReload = %v, %v; want SIGHUP (dhcpcd -n), never SIGALRM (dhcpcd -k)", got, err)
	}
}
